### ISSUE TITLE
message not sent

### ISSUE THREAD

**Issue by SwanyWu** [DrShahinstein/whatsapp-message-scheduler#1]
Hey, I wonder if the message will be sent as well or I need to click the 'send' button manually?
the text in target.json did show up in my dialog window (where you enter your message) but the send button was not triggered.

**Comment by DrShahinstein** [comment]
```python
def send_message():
    url = 'https://web.whatsapp.com/send?phone=' + element["target"] + '&text=' + element["message"]
    webbrowser.open(url)
    timer = threading.Timer(10, lambda: pyautogui.press("enter"))
    timer.run()
```
As you can see, pyautogui is going to press enter after the link to the direct message is opened and 10 seconds so your message will be delivered automatically. In the case where your browser needs to wait more than 10 seconds to load whatsapp, you might want to increase the delay of pressing enter.
Actually, I have never checked out this repo for a long time until I saw your issue and looks like I had much better ways to do this project. Maybe I can update this repo soon. Because it looks really primitive to me right now.
